### ISSUE TITLE
Ask for uploading the initial flow field 

### ISSUE THREAD

**Issue by Bingzheng-Han** [taehyuklee/TurbulenceControlCode#1]
if episode == "Test":
            #data_frame_init = pd.read_csv(r"/home/fish991/code/Half_staggered/Test_folder/Test_dudw/mid dataset/mid dataset epTest t_real10000.csv", encoding = "ISO-8859-1")
            data_frame_init = pd.read_csv(r"/home/fish991/code/Half_staggered/Env_wide/developed.csv", encoding = "ISO-8859-1")

In the test code, the initial flow field is used but no data is available, would you like to upload it?

**Comment by taehyuklee** [comment]
Completed of upload of developed.csv in Re_tau 180 Condition. refer to  `/initialField` directory in `TurbulenceControlCode` Repo. thank you for your interest in the paper.

**Comment by Bingzheng-Han** [comment]
Thanks!

**Comment by taehyuklee** [comment]
Completed of upload of developed.csv
